#!/usr/bin/env python3
"""Focused search for a genuine new direction from two separated cores.

The preceding single-core heterogeneous screen connected a five-atom path to
a topologically different five-atom tree at one atom.  It exposed seven target
anchors but remained three dimensions short.  A deterministic pilot comparing
two next mechanisms found:

* a legal local unicycle (the Katz--Tao four-atom molecule plus one leaf)
  remained three dimensions short; and
* two separated interface components placed at the endpoints of a common
  coloured edge improved the deficit from three dimensions to two.

This script therefore expands only the second mechanism.

Probability legality
--------------------
Every five-vertex coloured tree is generated by four successive conditional
copies, so all vertices have marginal U=(X,Y).  More importantly, the joint
law of the endpoints of an edge of colour R is the same standard conditional-
copy coupling for every tree containing that coloured edge.  Thus, if the
fixed path and a heterogeneous tree both contain an R-coloured edge, the two
endpoint pairs have identical joint laws.

For any two allowed projections P,Q we may consequently copy the two complete
tree molecules conditionally independently over

    W = (P(first endpoint), Q(second endpoint)).

When the two components are independent modulo the local constraints,
H(W)<=2M.  The two trees cost 8M and the interface costs 2M, leaving seven
encoding components at the meaningful target 17/10=1.7.

Search scope
------------
The fixed path has colours (X,X,X,Y).  The pilot's only one-dimension gains
used its unique Y-coloured terminal edge, so the focused family exhausts:

* all 851 rooted coloured star/fork motifs from the previous experiment;
* every Y-coloured edge in each motif, in both orientations; and
* all 16 ordered projection pairs (P,Q).

Constraint rowspaces are deduplicated.  A narrow exact-rank beam screens the
whole focused family; a stratified selection is rerun with a wider beam; and
the strongest near misses are exhaustively audited over every distinct
encoding rowspace of rank at most seven.  A negative outcome is a finite
screened-family result, not a theorem about every possible dual-core proof.
"""

from __future__ import annotations

from dataclasses import dataclass
from time import perf_counter
from typing import Sequence

from eight_atom_cycle_search import Edge, Observation, P, SLOPES, quotient_model
from heterogeneous_tertiary_fold_search import (
    SEED_BACKBONE,
    RootedMotif,
    rooted_motifs,
)
from protein_tertiary_fold_search import (
    constraint_signature,
    diverse_beam_search,
    exact_subspace_search,
    five_path_edges,
    format_observations,
)


N = 10
TARGET_TOTAL_COST = 17
COLLISION_COST = 10
ENCODING_BUDGET = TARGET_TOTAL_COST - COLLISION_COST
COARSE_WIDTH = 2
REFINE_WIDTH = 32
GLOBAL_REFINE_COUNT = 64
PER_STRATUM_REFINE_COUNT = 2
EXACT_AUDIT_COUNT = 3
LABELS = tuple(SLOPES)
SEED_EDGES = tuple(five_path_edges(SEED_BACKBONE, 0))
SEED_CORE_EDGE_INDEX = 3


@dataclass(frozen=True)
class DualCoreSpec:
    motif: RootedMotif
    motif_edge_index: int
    reverse: bool
    first_projection: str
    second_projection: str


@dataclass(frozen=True)
class SearchResult:
    spec: DualCoreSpec
    encoding: tuple[Observation, ...]
    anchors: tuple[int, ...]
    reconstruction_rank: int
    quotient_dimension: int
    feasible: bool
    rowspaces_evaluated: int


def edges_for(spec: DualCoreSpec) -> list[Edge]:
    seed_left, seed_right, seed_colour = SEED_EDGES[SEED_CORE_EDGE_INDEX]
    motif_left, motif_right, motif_colour = spec.motif.edges[spec.motif_edge_index]
    assert seed_colour == motif_colour == "Y"
    if spec.reverse:
        motif_left, motif_right = motif_right, motif_left
    edges = list(SEED_EDGES)
    edges.extend(
        (left + 5, right + 5, colour)
        for left, right, colour in spec.motif.edges
    )
    edges.extend(
        (
            (
                seed_left,
                motif_left + 5,
                spec.first_projection,
            ),
            (
                seed_right,
                motif_right + 5,
                spec.second_projection,
            ),
        )
    )
    return edges


def distinct_specs() -> tuple[list[DualCoreSpec], int, int]:
    raw = 0
    independent = 0
    representatives: dict[tuple, DualCoreSpec] = {}
    for motif in rooted_motifs():
        for edge_index, (_left, _right, colour) in enumerate(motif.edges):
            if colour != "Y":
                continue
            for reverse in (False, True):
                for first in LABELS:
                    for second in LABELS:
                        raw += 1
                        spec = DualCoreSpec(
                            motif,
                            edge_index,
                            reverse,
                            first,
                            second,
                        )
                        signature = constraint_signature(edges_for(spec))
                        # Eight independent local tree constraints plus two
                        # genuinely independent cross-interface components.
                        if len(signature) != COLLISION_COST:
                            continue
                        independent += 1
                        representatives.setdefault(signature, spec)
    return list(representatives.values()), raw, independent


def evaluate(spec: DualCoreSpec, width: int) -> SearchResult:
    model = quotient_model(N, edges_for(spec))
    assert model.constraint_rank == COLLISION_COST
    assert model.quotient_dimension == 10
    best, visited = diverse_beam_search(model, ENCODING_BUDGET, width=width)
    encoding = tuple(model.observation_labels[index] for index in best.indices)
    return SearchResult(
        spec=spec,
        encoding=encoding,
        anchors=best.check.anchors,
        reconstruction_rank=best.check.reconstruction_rank,
        quotient_dimension=model.quotient_dimension,
        feasible=best.check.feasible,
        rowspaces_evaluated=visited,
    )


def score(result: SearchResult) -> tuple[int, int, int]:
    return (
        int(result.feasible),
        result.reconstruction_rank,
        len(result.anchors),
    )


def stratum(result: SearchResult) -> tuple[str, bool, str, str]:
    spec = result.spec
    return (
        spec.motif.topology,
        spec.reverse,
        spec.first_projection,
        spec.second_projection,
    )


def coarse_screen(specs: Sequence[DualCoreSpec]) -> list[SearchResult]:
    results: list[SearchResult] = []
    started = perf_counter()
    for index, spec in enumerate(specs, start=1):
        result = evaluate(spec, COARSE_WIDTH)
        results.append(result)
        if result.feasible:
            break
        if index % 2000 == 0:
            best = max(results, key=score)
            print(
                f"coarse {index}/{len(specs)}; best="
                f"{best.reconstruction_rank}/{best.quotient_dimension}; "
                f"anchors={len(best.anchors)}",
                flush=True,
            )
    print(f"coarse folds evaluated = {len(results)}")
    print(
        f"coarse rowspaces evaluated = "
        f"{sum(result.rowspaces_evaluated for result in results)}"
    )
    print(f"coarse candidates = {sum(result.feasible for result in results)}")
    print(f"coarse elapsed seconds = {perf_counter() - started:.3f}")
    return results


def select_for_refinement(results: Sequence[SearchResult]) -> list[SearchResult]:
    selected: dict[DualCoreSpec, SearchResult] = {}
    ranked = sorted(results, key=score, reverse=True)
    for result in ranked[:GLOBAL_REFINE_COUNT]:
        selected[result.spec] = result

    buckets: dict[tuple[str, bool, str, str], list[SearchResult]] = {}
    for result in results:
        buckets.setdefault(stratum(result), []).append(result)
    for bucket in buckets.values():
        bucket.sort(key=score, reverse=True)
        for result in bucket[:PER_STRATUM_REFINE_COUNT]:
            selected[result.spec] = result
    return list(selected.values())


def refine(results: Sequence[SearchResult]) -> list[SearchResult]:
    selected = select_for_refinement(results)
    refined: list[SearchResult] = []
    started = perf_counter()
    for result in selected:
        rerun = evaluate(result.spec, REFINE_WIDTH)
        refined.append(rerun)
        if rerun.feasible:
            break
    refined.sort(key=score, reverse=True)
    print(f"stratified refined folds = {len(refined)}")
    print(
        f"refined rowspaces evaluated = "
        f"{sum(result.rowspaces_evaluated for result in refined)}"
    )
    print(f"refined candidates = {sum(result.feasible for result in refined)}")
    print(f"refine elapsed seconds = {perf_counter() - started:.3f}")
    return refined


def print_result(prefix: str, result: SearchResult) -> None:
    spec = result.spec
    print(prefix)
    print(f"  motif topology/root = {spec.motif.topology}/{spec.motif.root}")
    print(f"  motif edges = {spec.motif.edges}")
    print(
        f"  motif core edge / orientation = "
        f"{spec.motif.edges[spec.motif_edge_index]}/"
        f"{'reverse' if spec.reverse else 'parallel'}"
    )
    print(
        f"  interface projections = "
        f"({spec.first_projection}, {spec.second_projection})"
    )
    print(f"  encoding = {format_observations(result.encoding)}")
    print(f"  anchors = {result.anchors}")
    print(
        f"  reconstruction rank = {result.reconstruction_rank}/"
        f"{result.quotient_dimension}; feasible={result.feasible}"
    )


def exact_audit(results: Sequence[SearchResult]) -> None:
    print(f"\n[exact audit of strongest {EXACT_AUDIT_COUNT} focused folds]")
    for index, result in enumerate(results[:EXACT_AUDIT_COUNT], start=1):
        model = quotient_model(N, edges_for(result.spec))
        started = perf_counter()
        exact = exact_subspace_search(model, ENCODING_BUDGET)
        print(
            f"audit {index}: rowspaces={exact.rowspaces_tested}; "
            f"feasible={exact.feasible}; best="
            f"{exact.best_rank}/{exact.quotient_dimension}; "
            f"anchors={exact.best_anchors}; "
            f"seconds={perf_counter() - started:.3f}",
            flush=True,
        )


def main() -> None:
    print("Yuanjiang dual-separated-core tertiary search")
    print(f"rank prime = {P}")
    print("bound gate: 1.674733895 < 17/10 = 1.7 < 7/4")
    print("legality gate: matching Y-coloured core edges have identical pair laws")
    print("cost gate: local trees 8 + joint interface rank 2 + encoding 7 = 17")
    specs, raw, independent = distinct_specs()
    print(f"raw focused folds = {raw}")
    print(f"rank-two interface folds = {independent}")
    print(f"distinct constraint folds = {len(specs)}")
    coarse = coarse_screen(specs)
    if not coarse:
        print("no valid folds generated")
        return
    if any(result.feasible for result in coarse):
        refined = sorted(coarse, key=score, reverse=True)
    else:
        refined = refine(coarse)
    print("\n[strongest focused dual-core folds]")
    for index, result in enumerate(refined[:5], start=1):
        print_result(f"rank {index}:", result)
    exact_audit(refined)
    if refined[0].feasible:
        print("RESULT: a probability-legal 17/10 linear candidate was found")
    else:
        print(
            "RESULT: no 17/10 candidate in the focused dual-Y-core family; "
            "the best structures are two dimensions short"
        )


if __name__ == "__main__":
    main()
