#!/usr/bin/env python3
"""Protein-tertiary-structure-inspired arithmetic Kakeya search.

The biological inspiration is deliberately narrow: a protein starts as an
ordered chain, develops local motifs, and is compacted by a sparse set of
long-range contacts.  Here a five-atom open colored path is the local motif.
Two conditionally independent copies are glued over a sparse multi-residue
interface W, producing a ten-atom hierarchical fold.

Unlike the earlier 8-atom target 13/8=1.625, which is already below the known
four-slope lower bound (~1.674733895), the target here is

    10 H(X-Y) <= 17 M,       M=max H(X),H(Y),H(X+Y),H(X+2Y),

or 1.7.  This lies strictly between the known lower bound and Katz--Tao's 7/4
upper bound, so a valid candidate would be mathematically possible.

Legality of the construction
----------------------------
Each five-atom path is generated by four successive conditional copies over an
individual allowed projection, costing at most 4M.  The second whole path is a
conditional copy of the first over W.  If the independent rank of W is r, then
H(W)<=rM and the collision cost is a=8+r.  Every interface component is an
allowed projection at the same residue position in both copies, so the two W
tuples have identical joint distributions.  This is an ordinary copy-lemma
gluing, not merely a formal graph constraint.

The screen covers every reversal-inequivalent 4-color backbone (136 patterns),
a deterministic balanced sample of all two- and three-residue interfaces, and
structured five-residue interfaces (uniform, alternating, and palindromic
contact patterns).  For reversal-symmetric backbones it also includes
antiparallel interfaces.  Encoding search uses an exact-rank diverse beam; any
positive candidate is a valid certificate and is then checked by exhaustive
encoding search.  A zero screen is *not* an exhaustive no-go theorem for all W.
The strongest near misses are exhaustively audited.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from itertools import combinations, product
from time import perf_counter
from typing import Iterable, Sequence

from eight_atom_cycle_search import (
    Edge,
    EncodingCheck,
    Observation,
    P,
    RREF,
    SLOPES,
    check_encoding,
    collision_row,
    constraint_rows,
    format_observations,
    quotient_model,
    search_encodings,
)


N = 10
TARGET_TOTAL_COST = 17
BEAM_WIDTH = 32
EXACT_AUDIT_COUNT = 5
LABELS = tuple(SLOPES)


@dataclass(frozen=True)
class FoldSpec:
    backbone: tuple[str, ...]
    mode: str
    contacts: tuple[Observation, ...]
    mapping: tuple[int, ...]


@dataclass(frozen=True)
class FoldResult:
    spec: FoldSpec
    interface_rank: int
    collision_cost: int
    encoding_budget: int
    quotient_dimension: int
    encoding: tuple[Observation, ...]
    anchors: tuple[int, ...]
    reconstruction_rank: int
    feasible: bool
    beam_states: int


@dataclass
class BeamState:
    basis: RREF
    indices: tuple[int, ...]
    check: EncodingCheck


@dataclass(frozen=True)
class ExactSpaceResult:
    feasible: bool
    rowspaces_tested: int
    encoding: tuple[Observation, ...]
    anchors: tuple[int, ...]
    best_rank: int
    best_anchors: tuple[int, ...]
    quotient_dimension: int


def basis_signature(basis: RREF) -> tuple[tuple[int, tuple[int, ...]], ...]:
    return tuple((pivot, tuple(row)) for pivot, row in sorted(basis.rows.items()))


def constraint_signature(edges: Sequence[Edge]) -> tuple[tuple[int, tuple[int, ...]], ...]:
    return basis_signature(RREF(2 * N, constraint_rows(N, edges)))


def five_path_edges(backbone: Sequence[str], offset: int = 0) -> list[Edge]:
    return [
        (offset + atom, offset + atom + 1, label)
        for atom, label in enumerate(backbone)
    ]


def add_interface_basis(
    backbone: Sequence[str],
    contacts: Sequence[Observation],
    mapping: Sequence[int],
) -> tuple[list[Edge], int, tuple[Observation, ...]]:
    """Return two paths plus an independent basis of interface contacts."""
    edges = five_path_edges(backbone, 0) + five_path_edges(backbone, 5)
    constraints = RREF(2 * N, constraint_rows(N, edges))
    basis_contacts: list[Observation] = []
    for atom, label in contacts:
        right = 5 + mapping[atom]
        row = collision_row(N, atom, right, label)
        if constraints.add(row):
            edges.append((atom, right, label))
            basis_contacts.append((atom, label))
    return edges, len(basis_contacts), tuple(basis_contacts)


def evaluate_state(model, basis: RREF, indices: tuple[int, ...]) -> BeamState:
    anchors = tuple(
        atom
        for atom, target in enumerate(model.target_rows)
        if basis.contains(target)
    )
    reconstruction = basis.copy()
    for atom in anchors:
        reconstruction.add(model.x_rows[atom])
        reconstruction.add(model.y_rows[atom])
    check = EncodingCheck(
        feasible=reconstruction.rank == model.quotient_dimension,
        reconstruction_rank=reconstruction.rank,
        anchors=anchors,
    )
    return BeamState(basis=basis, indices=indices, check=check)


def state_score(state: BeamState) -> tuple[int, int, int, int]:
    # Reconstruction is primary.  Anchor-mask diversity is retained separately
    # below so a currently weaker state with a different propagation pattern is
    # not immediately discarded.
    return (
        int(state.check.feasible),
        state.check.reconstruction_rank,
        len(state.check.anchors),
        state.basis.rank,
    )


def diverse_beam_search(model, max_size: int, width: int = BEAM_WIDTH) -> tuple[BeamState, int]:
    initial_basis = RREF(model.quotient_dimension)
    states = [evaluate_state(model, initial_basis, ())]
    best = states[0]
    visited = 1

    for _depth in range(max_size + 1):
        for state in states:
            if state_score(state) > state_score(best):
                best = state
            if state.check.feasible:
                return state, visited
        if states and states[0].basis.rank >= max_size:
            break

        generated: dict[tuple[tuple[int, tuple[int, ...]], ...], BeamState] = {}
        for state in states:
            for index, row in enumerate(model.observation_rows):
                child_basis = state.basis.copy()
                if not child_basis.add(row):
                    continue
                signature = basis_signature(child_basis)
                if signature in generated:
                    continue
                child = evaluate_state(model, child_basis, state.indices + (index,))
                generated[signature] = child
        visited += len(generated)
        if not generated:
            break

        # Keep several states for every distinct anchor propagation pattern,
        # then take the globally strongest remainder.
        buckets: dict[tuple[int, ...], list[BeamState]] = {}
        for state in generated.values():
            buckets.setdefault(state.check.anchors, []).append(state)
        diverse: list[BeamState] = []
        for bucket in buckets.values():
            bucket.sort(key=state_score, reverse=True)
            diverse.extend(bucket[:2])
        diverse.sort(key=state_score, reverse=True)
        states = diverse[:width]

    return best, visited


def exact_subspace_search(model, max_size: int) -> ExactSpaceResult:
    """Exhaust all distinct observation-generated rowspaces up to max_size.

    Many different encoding subsets span the same rowspace and therefore have
    identical target/reconstruction behavior.  Enumerating each rowspace once
    is exact and substantially faster than enumerating every redundant subset.
    """
    initial = RREF(model.quotient_dimension)
    levels: dict[
        tuple[tuple[int, tuple[int, ...]], ...],
        tuple[RREF, tuple[int, ...]],
    ] = {basis_signature(initial): (initial, ())}
    tested = 0
    best_rank = -1
    best_anchors: tuple[int, ...] = ()

    for depth in range(max_size + 1):
        next_levels: dict[
            tuple[tuple[int, tuple[int, ...]], ...],
            tuple[RREF, tuple[int, ...]],
        ] = {}
        for basis, indices in levels.values():
            tested += 1
            state = evaluate_state(model, basis, indices)
            if (state.check.reconstruction_rank, len(state.check.anchors)) > (
                best_rank,
                len(best_anchors),
            ):
                best_rank = state.check.reconstruction_rank
                best_anchors = state.check.anchors
            if state.check.feasible:
                return ExactSpaceResult(
                    feasible=True,
                    rowspaces_tested=tested,
                    encoding=tuple(
                        model.observation_labels[index] for index in indices
                    ),
                    anchors=state.check.anchors,
                    best_rank=best_rank,
                    best_anchors=best_anchors,
                    quotient_dimension=model.quotient_dimension,
                )
            if depth == max_size:
                continue
            for index, row in enumerate(model.observation_rows):
                child = basis.copy()
                if not child.add(row):
                    continue
                signature = basis_signature(child)
                next_levels.setdefault(signature, (child, indices + (index,)))
        levels = next_levels

    return ExactSpaceResult(
        feasible=False,
        rowspaces_tested=tested,
        encoding=(),
        anchors=(),
        best_rank=best_rank,
        best_anchors=best_anchors,
        quotient_dimension=model.quotient_dimension,
    )


def canonical_backbones() -> tuple[tuple[str, ...], ...]:
    patterns = []
    for pattern in product(LABELS, repeat=4):
        if pattern <= tuple(reversed(pattern)):
            patterns.append(tuple(pattern))
    assert len(patterns) == 136
    return tuple(patterns)


def deterministic_sample(
    items: Sequence[tuple[Observation, ...]], count: int, salt: str
) -> tuple[tuple[Observation, ...], ...]:
    ranked = sorted(
        items,
        key=lambda item: sha256((salt + repr(item)).encode("utf-8")).digest(),
    )
    return tuple(ranked[: min(count, len(ranked))])


def pair_and_triple_interfaces() -> tuple[
    tuple[tuple[Observation, ...], ...],
    tuple[tuple[Observation, ...], ...],
]:
    pairs = tuple(
        tuple((atom, label) for atom, label in zip(atoms, labels))
        for atoms in combinations(range(5), 2)
        for labels in product(LABELS, repeat=2)
    )
    triples = tuple(
        tuple((atom, label) for atom, label in zip(atoms, labels))
        for atoms in combinations(range(5), 3)
        for labels in product(LABELS, repeat=3)
    )
    assert len(pairs) == 160 and len(triples) == 640
    return pairs, triples


def structured_full_interfaces() -> tuple[tuple[Observation, ...], ...]:
    patterns: set[tuple[str, ...]] = set()
    for label in LABELS:
        patterns.add((label,) * 5)
    for left in LABELS:
        for right in LABELS:
            patterns.add((left, right, left, right, left))
    for a, b, c in product(LABELS, repeat=3):
        patterns.add((a, b, c, b, a))
    assert len(patterns) == 64
    return tuple(
        tuple((atom, label) for atom, label in enumerate(pattern))
        for pattern in sorted(patterns)
    )


def generate_specs() -> Iterable[FoldSpec]:
    pairs, triples = pair_and_triple_interfaces()
    full = structured_full_interfaces()
    identity = tuple(range(5))
    reverse = tuple(reversed(range(5)))

    for backbone in canonical_backbones():
        salt = "|".join(backbone)
        selected = (
            deterministic_sample(pairs, 24, "pair:" + salt)
            + deterministic_sample(triples, 40, "triple:" + salt)
            + deterministic_sample(full, 16, "full:" + salt)
        )
        for contacts in selected:
            yield FoldSpec(backbone, "parallel", contacts, identity)

        # A fixed-color path is reversible precisely when its edge-color word
        # is palindromic.  Only then is the antiparallel boundary tuple
        # guaranteed to have the same joint law.
        if backbone == tuple(reversed(backbone)):
            anti = (
                deterministic_sample(pairs, 16, "anti-pair:" + salt)
                + deterministic_sample(triples, 24, "anti-triple:" + salt)
                + deterministic_sample(full, 8, "anti-full:" + salt)
            )
            for contacts in anti:
                yield FoldSpec(backbone, "antiparallel", contacts, reverse)


def run_screen() -> tuple[list[FoldResult], int, int]:
    seen_graphs: set[tuple[int, tuple[tuple[int, tuple[int, ...]], ...]]] = set()
    results: list[FoldResult] = []
    raw_specs = 0
    beam_states = 0
    started = perf_counter()

    print("[10-atom hierarchical protein-fold screen]")
    print(f"rank field prime = {P}; target total cost = {TARGET_TOTAL_COST}")
    for spec in generate_specs():
        raw_specs += 1
        edges, interface_rank, basis_contacts = add_interface_basis(
            spec.backbone, spec.contacts, spec.mapping
        )
        collision_cost = 8 + interface_rank
        encoding_budget = TARGET_TOTAL_COST - collision_cost
        if encoding_budget < 0:
            continue
        signature = (collision_cost, constraint_signature(edges))
        if signature in seen_graphs:
            continue
        seen_graphs.add(signature)

        model = quotient_model(N, edges)
        best, visited = diverse_beam_search(model, encoding_budget)
        beam_states += visited
        encoding = tuple(model.observation_labels[index] for index in best.indices)
        results.append(
            FoldResult(
                spec=FoldSpec(spec.backbone, spec.mode, basis_contacts, spec.mapping),
                interface_rank=interface_rank,
                collision_cost=collision_cost,
                encoding_budget=encoding_budget,
                quotient_dimension=model.quotient_dimension,
                encoding=encoding,
                anchors=best.check.anchors,
                reconstruction_rank=best.check.reconstruction_rank,
                feasible=best.check.feasible,
                beam_states=visited,
            )
        )
        if best.check.feasible:
            print("VALID 1.7 CANDIDATE FOUND; stopping for exhaustive audit")
            break
        if len(results) % 1000 == 0:
            best_so_far = max(
                results,
                key=lambda result: (
                    result.reconstruction_rank - result.quotient_dimension,
                    len(result.anchors),
                ),
            )
            print(
                f"unique folds={len(results)}; raw specs={raw_specs}; "
                f"best rank={best_so_far.reconstruction_rank}/"
                f"{best_so_far.quotient_dimension}; "
                f"anchors={len(best_so_far.anchors)}",
                flush=True,
            )

    elapsed = perf_counter() - started
    print(f"raw fold specifications = {raw_specs}")
    print(f"distinct cost-aware folds = {len(results)}")
    print(f"beam rowspaces evaluated = {beam_states}")
    print(f"beam candidates = {sum(result.feasible for result in results)}")
    print(f"elapsed seconds = {elapsed:.3f}")
    return results, raw_specs, beam_states


def result_score(result: FoldResult) -> tuple[int, int, int, int]:
    return (
        int(result.feasible),
        result.reconstruction_rank - result.quotient_dimension,
        len(result.anchors),
        -result.interface_rank,
    )


def print_result(prefix: str, result: FoldResult) -> None:
    print(prefix)
    print(f"  backbone colors = {result.spec.backbone}")
    print(f"  fold mode = {result.spec.mode}")
    print(f"  independent interface = {format_observations(result.spec.contacts)}")
    print(
        f"  interface rank/collision cost/encoding budget = "
        f"{result.interface_rank}/{result.collision_cost}/{result.encoding_budget}"
    )
    print(f"  encoding = {format_observations(result.encoding)}")
    print(f"  anchors = {result.anchors}")
    print(
        f"  reconstruction rank = {result.reconstruction_rank}/"
        f"{result.quotient_dimension}; feasible={result.feasible}"
    )


def exact_audit(results: Sequence[FoldResult]) -> None:
    ranked = sorted(results, key=result_score, reverse=True)
    selected: list[FoldResult] = []
    signatures: set[tuple] = set()
    for result in ranked:
        signature = (
            result.spec.backbone,
            result.spec.mode,
            result.spec.contacts,
            result.interface_rank,
        )
        if signature in signatures:
            continue
        signatures.add(signature)
        selected.append(result)
        if len(selected) == EXACT_AUDIT_COUNT:
            break

    print(f"\n[exhaustive audit of {len(selected)} strongest beam near misses]")
    exact_candidates = 0
    for index, result in enumerate(selected, start=1):
        edges, interface_rank, _ = add_interface_basis(
            result.spec.backbone, result.spec.contacts, result.spec.mapping
        )
        model = quotient_model(N, edges)
        exact = exact_subspace_search(
            model, TARGET_TOTAL_COST - (8 + interface_rank)
        )
        if exact.feasible:
            exact_candidates += 1
        print(
            f"audit {index:02d}: distinct rowspaces={exact.rowspaces_tested}; "
            f"exact feasible={exact.feasible}; best rank="
            f"{exact.best_rank}/{exact.quotient_dimension}; "
            f"anchors={exact.best_anchors}",
            flush=True,
        )
    print(f"exact candidates among audited near misses = {exact_candidates}")


def main() -> None:
    print("Yuanjiang protein-tertiary-fold search")
    print("meaningful target: 17/10 = 1.7 (known lower < 1.7 < 7/4)")
    results, _, _ = run_screen()
    if not results:
        print("no folds generated")
        return
    ranked = sorted(results, key=result_score, reverse=True)
    print("\n[strongest screened folds]")
    for index, result in enumerate(ranked[:5], start=1):
        print_result(f"screen rank {index}:", result)
    if ranked[0].feasible:
        print("\n[exhaustive verification of positive candidate]")
        result = ranked[0]
        edges, interface_rank, _ = add_interface_basis(
            result.spec.backbone, result.spec.contacts, result.spec.mapping
        )
        exact = exact_subspace_search(
            quotient_model(N, edges), TARGET_TOTAL_COST - (8 + interface_rank)
        )
        print(
            f"exhaustive feasible = {exact.feasible}; "
            f"distinct rowspaces = {exact.rowspaces_tested}"
        )
        print(f"encoding = {format_observations(exact.encoding)}")
        print(f"anchors = {exact.anchors}")
    else:
        exact_audit(ranked)
        print(
            "\nInterpretation: no 1.7 candidate was found in this deterministic "
            "protein-fold screen.  This is a screened-family negative result, "
            "not an exhaustive no-go theorem for all tertiary interfaces."
        )


if __name__ == "__main__":
    main()
